CREATE TABLE [dbo].[ToolSetupSheet] (
    [ID]                       INT           IDENTITY (1, 1) NOT NULL,
    [MachineType]              VARCHAR (20)  NULL,
    [PartNumber]               VARCHAR (50)  NULL,
    [Revision]                 VARCHAR (20)  NULL,
    [Operation]                INT           NULL,
    [InputDate]                DATETIME      CONSTRAINT [DF_ToolSetupSheet_InputDate] DEFAULT (getdate()) NULL,
    [Machine]                  VARCHAR (50)  NULL,
    [ProgramNumber]            VARCHAR (50)  NULL,
    [ProgramLocation]          VARCHAR (100) NULL,
    [UOM]                      VARCHAR (20)  NULL,
    [MaterialType]             VARCHAR (50)  NULL,
    [MaterialHeatTreated]      VARCHAR (50)  NULL,
    [MaterialForm]             VARCHAR (50)  NULL,
    [MaterialSize]             VARCHAR (20)  NULL,
    [MachineWorkHoldingTo]     VARCHAR (20)  NULL,
    [CutWorkHoldingTo]         VARCHAR (20)  NULL,
    [workHolding1ItemNumber]   VARCHAR (20)  NULL,
    [workHolding1ImagePath]    VARCHAR (100) NULL,
    [workHolding2ItemNumber]   VARCHAR (20)  NULL,
    [workHolding2ImagePath]    VARCHAR (100) NULL,
    [workHolding3ItemNumber]   VARCHAR (20)  NULL,
    [workHolding3ImagePath]    VARCHAR (100) NULL,
    [workHolding1MWID]         VARCHAR (20)  NULL,
    [workHolding2MWID]         VARCHAR (20)  NULL,
    [workHolding3MWID]         VARCHAR (20)  NULL,
    [workHolding1Location]     VARCHAR (50)  NULL,
    [workHolding2Location]     VARCHAR (50)  NULL,
    [workHolding3Location]     VARCHAR (50)  NULL,
    [workHoldingComments]      VARCHAR (200) NULL,
    [workHoldingImageNoPart]   VARCHAR (50)  NULL,
    [workHoldingImageWithPart] VARCHAR (50)  NULL,
    [workHoldingImageComplete] VARCHAR (50)  NULL,
    [Torque]                   VARCHAR (20)  NULL,
    [HoldPartOn]               VARCHAR (20)  NULL,
    [Z0]                       VARCHAR (20)  NULL,
    [BarStickOutBefore]        VARCHAR (20)  NULL,
    [FaceOff]                  VARCHAR (20)  NULL,
    [CutOffToolThickness]      VARCHAR (20)  NULL,
    [OAL]                      VARCHAR (20)  NULL,
    [BarStickOutAfter]         VARCHAR (20)  NULL,
    [BarPullOut]               VARCHAR (20)  NULL,
    [PartStickOutMinimum]      VARCHAR (20)  NULL,
    [Comments]                 VARCHAR (200) NULL,
    [Program]                  VARCHAR (MAX) NULL,
    [ProgramProven]            BIT           CONSTRAINT [DF_ToolSetupSheet_ProgramProven] DEFAULT ((0)) NULL,
    [Created]                  DATETIME      NULL,
    [CreatedBy]                VARCHAR (20)  NULL,
    [Modified]                 DATETIME      NULL,
    [ModifiedBy]               VARCHAR (20)  NULL,
    CONSTRAINT [PK_ToolSetupSheet] PRIMARY KEY CLUSTERED ([ID] ASC)
);

